name: Auto Bump Version and Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js (v22)
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # Update to match your project
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Bump Version
        run: |
          pnpm version patch --no-git-tag-version
          git add package.json
          git commit -m "chore: bump version [skip ci]"
          git push

      - name: Deploy to Vercel
        run: |
          pnpm dlx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
					