name: Auto Bump Version and Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install PNPM
        run: npm i -g pnpm
      - name: Install & Build
        run: pnpm i && pnpm build
      - name: Bump Version
        run: |
          pnpm version patch --no-git-tag-version
          git add package.json
          git commit -m "chore: bump version [skip ci]"
          git push

      - name: Deploy to Vercel
        run: |
          pnpm dlx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
